// Generated by CoffeeScript 1.9.3
(function() {
  var logWithTime, moment, util,
    slice = [].slice;

  util = require('util');

  moment = require('moment');

  logWithTime = function() {
    var args, time;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    time = moment().format('MM-DD HH:mm:ss');
    return console.log.apply(console, [time].concat(slice.call(args)));
  };

  module.exports = function(modName) {
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      try {
        if (args[0].slice(0, 2) === 'i ') {
          args = [
            args[0].slice(2), util.inspect(args[1], {
              depth: null
            })
          ];
        }
      } catch (_error) {}
      return logWithTime.apply(null, [modName.toLowerCase() + ' '].concat(slice.call(args)));
    };
  };

}).call(this);
